[package]
name = "r2d2_sqlite"
version = "0.1.0"
license = "MIT"
description = "SQLite support for the r2d2 connection pool"
repository = "https://github.com/gwenn/r2d2-sqlite"
keywords = ["sqlite", "sql", "pool", "database"]

[lib]
name = "r2d2_sqlite"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
r2d2 = "0.6"

[dependencies.rusqlite]
git = "https://github.com/gwenn/rusqlite.git"
branch = "r2d2"