name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install libsqlite3-dev
        run: sudo apt-get install libsqlite3-dev
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
